# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Unity
  # You may pin to the exact commit or the version.
  # uses: kuler90/setup-unity@b88bc2f8c9e0981089e09c8c6d8b0bea169b1b30
        uses: kuler90/setup-unity@v1.0.6
        with:
          unity-modules: windows-mono, linux-mono, mac-il2cpp
          # Automatically installs all child modules of selected modules. For example, android-open-jdk and android-sdk-ndk-tools for android

      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          
      - name: Build Unity
        uses: kuler90/build-unity@v1
        with:
          build-method: Builder.BuildGame
          build-method-args: '["./build", "StandaloneWindows", "StandaloneWindows", "StandaloneWindows", "StandaloneWindows"]'
          
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneWindows
          VERSION_FILE: ./build/version.txt
          
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneWindows64
          VERSION_FILE: ./build/version.txt
          
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneLinux64
          VERSION_FILE: ./build/version.txt
          
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneOSX
          VERSION_FILE: ./build/version.txt


