# This is a basic workflow to help you get started with Actions

name: Build and Publish All
# Can perhaps be split into seperate build and publish workflows.

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: webbertakken/unity-builder@v2.0-aplha-5
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_USERNAME }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
        with:
          unityVersion: 2019.4.12f1
          buildMethod: Builder.CDBuildGame
      
  publish-win32:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneWindows
          VERSION_FILE: ./build/version.txt
          
  publish-win64:
    needs: build
    runs-on: ubuntu-latest
    steps:
          
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneWindows64
          VERSION_FILE: ./build/version.txt
          
  publish-linux:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneLinux64
          VERSION_FILE: ./build/version.txt
          
  publish-osx:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ./build/StandaloneOSX
          VERSION_FILE: ./build/version.txt


