# This is a basic workflow to help you get started with Actions

name: Build and Publish All
# Can perhaps be split into seperate build and publish workflows.

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: webbertakken/unity-builder@v1.5
        with:
          buildMethod: Builder.CDBuildGame
          unityVersion: 2019.4.12f1
          
      - run: ls -R
      
      - uses: actions/upload-artifact@v2
        with:
          name: BFA2-Build
          path: ./build/
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [./build/Win32, ./build/Win64, ./build/Linux, ./build/OSX]
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: BFA2-Build
          path: ./build/
      
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Brute-Force-Attack-2
          ITCH_USER: Lomztein
          PACKAGE: ${{ matrix.target }}
          VERSION_FILE: ./build/version.txt
